"""initial schema

Revision ID: 9d5942d5f4db
Revises:
Create Date: 2026-06-22 20:09:35.160793
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "9d5942d5f4db"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contacts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("wa_id", sa.String(length=32), nullable=False),
        sa.Column("profile_name", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contacts")),
        sa.UniqueConstraint("wa_id", name=op.f("uq_contacts_wa_id")),
    )
    op.create_table(
        "webhook_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("signature_valid", sa.Boolean(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webhook_events")),
    )
    op.create_index(
        op.f("ix_webhook_events_created_at"), "webhook_events", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_webhook_events_source"), "webhook_events", ["source"], unique=False)
    op.create_table(
        "whatsapp_messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("contact_id", sa.UUID(), nullable=True),
        sa.Column("meta_message_id", sa.String(length=255), nullable=True),
        sa.Column("direction", sa.String(length=16), nullable=False),
        sa.Column("message_type", sa.String(length=64), nullable=False),
        sa.Column("text_body", sa.Text(), nullable=True),
        sa.Column("media_id", sa.String(length=255), nullable=True),
        sa.Column("media_mime_type", sa.String(length=255), nullable=True),
        sa.Column("location_latitude", sa.Float(), nullable=True),
        sa.Column("location_longitude", sa.Float(), nullable=True),
        sa.Column("location_name", sa.String(length=255), nullable=True),
        sa.Column("location_address", sa.Text(), nullable=True),
        sa.Column("location_url", sa.Text(), nullable=True),
        sa.Column("raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
            name=op.f("fk_whatsapp_messages_contact_id_contacts"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_whatsapp_messages")),
        sa.UniqueConstraint("meta_message_id", name=op.f("uq_whatsapp_messages_meta_message_id")),
    )
    op.create_index(
        op.f("ix_whatsapp_messages_contact_id"), "whatsapp_messages", ["contact_id"], unique=False
    )
    op.create_index(
        op.f("ix_whatsapp_messages_received_at"), "whatsapp_messages", ["received_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_whatsapp_messages_received_at"), table_name="whatsapp_messages")
    op.drop_index(op.f("ix_whatsapp_messages_contact_id"), table_name="whatsapp_messages")
    op.drop_table("whatsapp_messages")
    op.drop_index(op.f("ix_webhook_events_source"), table_name="webhook_events")
    op.drop_index(op.f("ix_webhook_events_created_at"), table_name="webhook_events")
    op.drop_table("webhook_events")
    op.drop_table("contacts")
    # ### end Alembic commands ###
